app1/urls.py
from django.urls import path
from app1.views import *
app_name='one'
urlpatterns=[ 
    path('first/',first,name='first')
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='two'
urlpatterns=[ 
    path('second/',second,name='second')
]

app3/urls.py
from django.urls import path
from app3.views import *
app_name='three'
urlpatterns=[ 
    path('third/',third,name='third')
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2,app3

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('app3/',include('app3.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def first(request):
    return render(request,'first.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def second(request):
    return render(request,'second.html')

app3/views.py
from django.shortcuts import render

# Create your views here.
def third(request):
    return render(request,'third.html')

templates/first.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log In Form</title>
    <link rel="stylesheet" href="{% static 'css/first.css' %}">
</head>
<body>
    <h1>WELCOME !</h1>
    <div>
        <label for="username">USER NAME :</label>
        <input type="text" id="username">
    </div>
    <p></p>
    <div>
        <label for="password">PASSWORD :</label>
        <input type="password" id="password">
    </div>
    <p></p>
    <div id="button">
        <a href="{% url 'three:third' %}"><button>LOGIN</button></a>    
    </div>
    <p></p>
    <div>
        <a href="{% url 'two:second' %}">Register?</a>
    </div>
</body>
</html>

templates/ravi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
    <style>
        body
        {
            background-color: blue;
            color: aqua;
        }
    </style>
</head>
<body>
    <h1>My name is Ravikiran</h1>
    
</body>
</html>

templates/second.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/second.css' %}">
</head>
<body>
    <h1>REGISTRATION FORM</h1>
    <div>
        <label for="first">FIRST NAME :</label>
        <input type="text" id="first">
    </div>
    <p></p>
    <div>
        <label for="last">LAST NAME :</label>
        <input type="text" id="last">
    </div>
    <p></p>
    <div>
        <label for="surname">SURNAME :</label>
        <input type="text,mail-id,number" id="surname">
    </div>
    <p></p>
    <div>
        <label for="mail">E-MAIL ID :</label>
        <input type="text,mail-id,number" id="mail">
    </div>
    <p></p>
    <div>
        <label for="dob">DATE-OF-BIRTH :</label>
        <input type="date" id="DOB">
    </div>
    <p></p>
    <div>
        <label for="gender">GENDER :</label>
        <input type="radio" name="gender choice" value="choice 1">MALE
        <input type="radio" name="gender choice" value="choice 2">FEMALE
        <input type="radio" name="gender choice" value="choice 3">OTHERS
    </div>
    <p></p>
    <div>
        <label for="number">MOBILE NUMBER :</label>
        <input type="+91-10-digit" id="number">
    </div>
    <p></p>
    <div>
        <label for="password">PASSWORD:</label>
        <input type="text" id="password">
    </div>
    <div>
        <label for="password">CONFIRM PASSWORD:</label>
        <input type="text" id="confirm password">
    </div>
    <p></p>
    <div id="button">
        <a href="{% url 'one:first' %}"><button>SUBMIT</button></a>
    </div>
    <p></p>
</body>
</html>

templates/third.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/third.css' %}">
    <title>LEARNING</title>
  </head>
  <body>
    <center><marquee behavior="scroll" direction="left"><h1>WELCOME TO LEARNING</h1></marquee></center>
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="https://img.lovepik.com/photo/50089/0761.jpg_wh860.jpg" class="d-block w-100" alt="..." width="100px" height="700px">
            <div class="carousel-caption d-none d-md-block">
              <h5 id="asd">SPEAKING THE LANGUAGE</h5>
            </div>
          </div>
          <div class="carousel-item">
            <img src="https://static.vecteezy.com/system/resources/previews/002/272/094/original/happy-women-student-gratuated-from-education-background-concept-free-vector.jpg" class="d-block w-100" alt="..." width="100px" height="700px">
            <div class="carousel-caption d-none d-md-block">
              <h5 id="zxc">ADAPTING TO THEIR SCHEDULE</h5>
            </div>
          </div>
          <div class="carousel-item">
            <img src="http://st2.depositphotos.com/1152339/9869/i/450/depositphotos_98697908-Education-background-School-Board-with-Painted-Hand-Drawn-Education-Icons.jpg" class="d-block w-100" alt="..."width="100px" height="700px">
            <div class="carousel-caption d-none d-md-block">
              <h5 id="qwe">HAVING SPECIFIC CAMPAIGNS</h5>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-target="#carouselExampleCaptions" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-target="#carouselExampleCaptions" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </button>
      </div>
    <a href="{% url 'one:first' %}"><button>LOG OUT</button></a>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>